cc_binary(
   name = 'thread_print',
   srcs = [
       'thread_print.cpp',
   ],
   incs = [
   ],
   deps = [
   ],

    extra_cppflags = [
        '-std=c++11',
        '-Wall',
        '-Wextra',
        '-Wno-deprecated',
    ],
)

cc_binary(
   name = 'words_count',
   srcs = [
       'words_count.cpp',
   ],
   incs = [
   ],
   deps = [
   ],

    extra_cppflags = [
        '-std=c++11',
        '-Wall',
        '-Wextra',
        '-Wno-deprecated',
    ],
)

