cc_library(
   name = 'binary_search',
   srcs = [
       'binary_search.cpp',
   ],
   incs = [
   ],
   deps = [
   ],

    extra_cppflags = [
        '-std=c++11',
        '-Wall',
        '-Wextra',
        '-Wno-deprecated',
    ],
)

cc_test(
   name = 'test',
   srcs = [
       'test.cpp',
   ],
   incs = [
   ],
   deps = [
   ],

    extra_cppflags = [
        '-std=c++11',
        '-Wall',
        '-Wextra',
        '-Wno-deprecated',
    ],
)