cc_binary(
   name = 'access_mem',
   srcs = [
       'access_mem.cpp',
   ],
   incs = [
   ],
   deps = [
   ],

    extra_cppflags = [
        '-std=c++11',
        '-Wall',
        '-Wextra',
        '-Wno-deprecated',
    ],
)

cc_binary(
   name = 'lru',
   srcs = [
       'lru.cpp',
   ],
   incs = [
   ],
   deps = [
   ],

    extra_cppflags = [
        '-std=c++11',
        '-Wall',
        '-Wextra',
        '-Wno-deprecated',
    ],
)

