cc_binary(
   name = 'list_node',
   srcs = [
       'list_node.cpp',
   ],
   incs = [
       
   ],
   deps = [
   ],

    extra_cppflags = [
        '-std=c++11',
        '-Wall',
        '-Wextra',
        '-Wno-deprecated',
    ],
)
