cc_binary(
   name = 'sort',
   srcs = [
       'sort.cpp',
   ],
   incs = [
   ],
   deps = [
   ],

    extra_cppflags = [
        '-std=c++11',
        '-Wall',
        '-Wextra',
        '-Wno-deprecated',
    ],
)
